import "./globals.css";
import clsx from "clsx";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppProvider from "./provider";

import "@rainbow-me/rainbowkit/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={clsx(inter.className, "bg-black")}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
